version: '3'
services:
  database:
    build: db/
    image: mysql:5.6
    command: --disable-partition-engine-check
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - ENV MYSQL_DATABASE=reviews
      - ENV MYSQL_USER=root
    ports:
      - 3306:3306

  reviews:
    build: ./
    depends_on:
      - 'database'
    restart: on-failure
    ports:
      - '3011:3011'
